version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_net
    depends_on:
      - webserver
    ports:
      - "9000:9000"

  webserver:
    image: nginx:stable-alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8081:80" # ✅ Ganti dari 8080 ke 8081
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_net

networks:
  laravel_net:
